export const SET_TIMER = "SET_TIMER";
export const SET_CURRENT_SEESION = "SET_CURRENT_SEESION";
export const SET_SHORTBREAK = "SET_SHORTBREAK";
export const SET_SHORTBREAK_SESSION = "SET_SHORTBREAK_SEESION";
export const SET_LONGBREAK = "SET_LONGBREAK";
export const SET_LONGBREAK_SESSION = "SET_LONGBREAK_SESSION";
export const DECREMENT_TIMER = "DECREMENT_TIMER";
export const DECREMENT_SHORTBREAK = "DECREMENT_SHORTBREAK";
export const DECREMENT_LONGBREAK = "DECREMENT_LONGBREAK";
export const RESET_TIMER = "RESET_TIMER";
export const CHOOSE_TIMER = "CHOOSE_TIMER";

export const SETBLOCK_MODAL = "SETBLOCK_MODAL";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const CLOSE_SETTINGS = "CLOSE_SETTINGS";
export const SET_DARKMODE = "SET_DARKMODE";

export const TOGGLE_LOGIN_MODAL = "TOGGLE_LOGIN_MODAL";
export const CLOSE_LOGIN = "CLOSE_LOGIN";
export const SET_USER = "SET_USER";
