export const SET_TIMER = "SET_TIMER";
export const SET_CURRENT_SEESION = "SET_CURRENT_SEESION";
export const SET_SHORTBREAK = "SET_SHORTBREAK";
export const SET_SHORTBREAK_SESSION = "SET_SHORTBREAK_SEESION";
export const SET_LONGBREAK = "SET_LONGBREAK";
export const SET_LONGBREAK_SESSION = "SET_LONGBREAK_SESSION";
export const DECREMENT_TIMER = "DECREMENT_TIMER";
export const DECREMENT_SHORTBREAK = "DECREMENT_SHORTBREAK";
export const DECREMENT_LONGBREAK = "DECREMENT_LONGBREAK";
export const RESET_TIMER = "RESET_TIMER";
export const CHOOSE_TIMER = "CHOOSE_TIMER";

export const SETBLOCK_MODAL = "SETBLOCK_MODAL";
export const TOGGLE_MODAL = "TOGGLE_MODAL";
export const SET_DARKMODE = "SET_DARKMODE";

export const ADD_TASK = "ADD_TASK";
export const SET_TASK = "SET_TASK";
export const DELETE_TASK = "DELETE_TASK";
